### ISSUE TITLE
Doesn't build  with nim-0.19.0-1

### ISSUE THREAD

**Issue by cbowman57** [kitsunyan/pakku#39] opened 2018-11-06 11:46 UTC
nim-0.19.0-1 is now in community-testing (Arch Linux)
This is what comes up when attempting to build either pakku or pakku-git:

GEN: doc/pakku.conf.5
tools.nim(1, 8) Error: cannot open file: os
make: *** [Makefile:117: lib/tools] Error 1
make: *** Waiting for unfinished jobs....
main.nim(2, 3) Error: cannot open file: future
make: *** [Makefile:123: src/pakku] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'pakku'

**Comment by mrvik** [comment] 2018-11-06 15:06
Duplicate of #36

**Comment by kitsunyan** [comment] 2018-11-06 15:09
0.19.0-1 is a broken package from community-_testing_ repo, almost nothing can be built without some hacks (e.g. symlinking config file into project dir).

**Closed by kitsunyan** 2018-11-06 15:09 UTC
